/alpha_rise/fls_pcl_node:
  ros__parameters:
    max_depth: -1.0 #World Frame (ENU)
    min_depth: -20.0 #World Frame (ENU)
    threshold_intensity: 125 #0-255 pixel values
    threshold_min_range: 5.0 #m
    threshold_max_range: 40.0 #m
    vertical_beamwidth: 12.0 # degrees
    frame_id: 'alpha_rise/fls_link'
    ping_sub_topic: '/alpha_rise/oculus/ping'
    image_sub_topic: '/alpha_rise/oculus/raw_image'
    marker_sub_topic: '/alpha_rise/fls/geometry'
    pointcloud_pub_topic: '/alpha_rise/fls/pointcloud/post'
    filter_mode: 'probabilistic_intensity' # threshold_intensity/max_intensity/probabilistic_intensity

    ## Stonefish
    # frame_id: 'alpha_rise/fls_link_sf'
    # image_sub_topic: '/alpha_rise/stonefish/fls/data/image'
    # pointcloud_sub_topic: '/alpha_rise/fls/pointcloud'
    
    # process every (int) beam into pointcloud. (1 - 512)
    beam_skip_count: 1

    save_as_pcd: False
    pcd_filename: "output_full_distance.pcd"