fls_params:
  horizontal_beamwidth: 70 #degrees
  max_range: 40 #m
  intensity_threshold: 30
  range_threshold: 10 #m
  frame_id: 'alpha_rise/fls_link_sf'
  
  # process every (int) beam into pointcloud. (1 - 512)
  beam_skip_count: 10