/alpha_rise/voxel_log_odds_visualizer:
  ros__parameters:
      # Volume of individual voxel
      voxel_resolution: 1.0
      
      # Volume of the voxel map. (m)
      grid_size: 400.0

      # Min logodds value to clip at.
      logodds_min: -20.0

      # Max logodds value to clip at.
      logodds_max: 20.0

      # Frame of the map
      frame_id: "alpha_rise/odom"
      
      # Only the voxels above this probablity is visualized
      probability_threshold: 0.9

      # Pointcloud topic to subscribe
      sub_pointcloud_topic:  "/alpha_rise/fls/pointcloud/post"
      # sub_pointcloud_topic:  "/alpha_rise/msis/pointcloud/fan"

      pub_pointcloud_topic: "/occupancy_grid"
      
      output_pcd_file: "fls_voxel_prob_full_map.pcd"

      save_pcd: false